name: Native S3 Huggingface tokenizers

on:
  workflow_dispatch:

jobs:
  build-tokenizers-jni-linux:
    runs-on: ubuntu-latest
    container: centos:centos7
    steps:
      - name: Install Environment
        run: |
          yum -y update
          yum -y install centos-release-scl-rh epel-release
          yum -y install devtoolset-7 git patch cmake3 libstdc++-static
          ln -s /usr/bin/cmake3 /usr/bin/cmake
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          pip3 install awscli --upgrade
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3 with the AWS CLI
        shell: bash
        run: |
          curl -O https://raw.githubusercontent.com/xyang16/djl-serving/xyang16-patch-3/serving/THIRD-PARTY-LICENSES
          aws s3 cp THIRD-PARTY-LICENSES s3://djl-ai/publish/dlc-licenses/huggingface/tgi-0.9.3/
          aws cloudfront create-invalidation --distribution-id E371VB8JQ6NRVY --paths "/dlc-licenses/huggingface/*"
