name: Native S3 Huggingface tokenizers

on:
  workflow_dispatch:

jobs:
  build-tokenizers-jni-linux:
    runs-on: ubuntu-latest
    container: centos:centos7
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3 with the AWS CLI
        shell: bash
        run: |
          aws s3 cp s3://djl-misc/spark/libs/vllm-0.0.0-cp39-cp39-linux_x86_64.whl .
          aws s3 cp vllm-0.0.0-cp39-cp39-linux_x86_64.whl s3://djl-ai/publish/vllm/
          aws cloudfront create-invalidation --distribution-id E371VB8JQ6NRVY --paths "/vllm/*"
